"use server";
import { clerkClient } from "@clerk/nextjs/server";
import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";
import { courseSchema, scheduleSchema, studentSchema, teacherSchema, updateStudentSchema } from "@/lib/validations/admin";

const ok = { success: true as const };
const err = (error: string) => ({ success: false as const, error });
export async function createStudent(formData: FormData) { try { const v=studentSchema.parse(Object.fromEntries(formData)); const clerk=await clerkClient(); const cu=await clerk.users.createUser({emailAddress:[v.email],publicMetadata:{role:"STUDENT"},firstName:v.firstName,lastName:v.lastName}); const count=await prisma.studentProfile.count(); const user=await prisma.user.create({data:{clerkId:cu.id,role:"STUDENT",firstName:v.firstName,lastName:v.lastName,email:v.email,phone:v.phone,gender:v.gender,dateOfBirth:v.dateOfBirth?new Date(v.dateOfBirth):undefined,address:v.address,studentProfile:{create:{studentCode:`EXC-${new Date().getFullYear()}-${String(count+1).padStart(3,"0")}`,guardianName:v.guardianName,guardianPhone:v.guardianPhone,emergencyContact:v.emergencyContact,notes:v.notes,enrollments:{create:{courseId:v.courseId,startDate:new Date(v.startDate)}}}}}}); revalidatePath("/admin/students"); return ok;} catch(e){return err(e instanceof Error?e.message:"Failed to create student");}}
export async function updateStudent(id:string, formData:FormData){try{const v=updateStudentSchema.parse(Object.fromEntries(formData)); await prisma.user.update({where:{id},data:{firstName:v.firstName,lastName:v.lastName,email:v.email,phone:v.phone,gender:v.gender,address:v.address,dateOfBirth:v.dateOfBirth?new Date(v.dateOfBirth):undefined,studentProfile:{update:{guardianName:v.guardianName,guardianPhone:v.guardianPhone,emergencyContact:v.emergencyContact,notes:v.notes}}}}); revalidatePath(`/admin/students/${id}`); return ok;}catch(e){return err(e instanceof Error?e.message:"Failed");}}
export async function deleteStudent(id:string){try{await prisma.enrollment.updateMany({where:{student:{userId:id}},data:{status:"DROPPED"}}); revalidatePath("/admin/students"); return ok;}catch(e){return err("Failed");}}
export async function createCourse(formData:FormData){try{const v=courseSchema.parse(Object.fromEntries(formData)); await prisma.course.create({data:v}); revalidatePath("/admin/courses"); return ok;}catch(e){return err("Failed");}}
export async function updateCourse(id:string,formData:FormData){try{const v=courseSchema.partial().parse(Object.fromEntries(formData)); await prisma.course.update({where:{id},data:v}); revalidatePath(`/admin/courses/${id}`); return ok;}catch(e){return err("Failed");}}
export async function createTeacher(formData:FormData){try{const v=teacherSchema.parse(Object.fromEntries(formData)); const clerk=await clerkClient(); const cu=await clerk.users.createUser({emailAddress:[v.email],publicMetadata:{role:"TEACHER"},firstName:v.firstName,lastName:v.lastName}); const c=await prisma.teacherProfile.count(); await prisma.user.create({data:{clerkId:cu.id,role:"TEACHER",firstName:v.firstName,lastName:v.lastName,email:v.email,phone:v.phone,gender:v.gender,teacherProfile:{create:{teacherCode:`TCH-${String(c+1).padStart(3,"0")}`,specialty:v.specialty,bio:v.bio}}}}); revalidatePath("/admin/teachers"); return ok;}catch(e){return err("Failed");}}
export async function createSchedule(formData:FormData){try{const v=scheduleSchema.parse(Object.fromEntries(formData)); await prisma.schedule.create({data:v}); revalidatePath("/admin/schedules"); return ok;}catch(e){return err("Failed");}}
export async function replyToReport(reportId:string, content:string){try{if(!content) return err("Content required"); await prisma.report.update({where:{id:reportId},data:{replyContent:content,repliedAt:new Date(),status:"REPLIED"}}); revalidatePath(`/admin/reports/${reportId}`); return ok;}catch(e){return err("Failed");}}

export async function markReportRead(reportId:string){try{const report=await prisma.report.findUnique({where:{id:reportId}});if(report?.status==="UNREAD"){await prisma.report.update({where:{id:reportId},data:{status:"READ"}});} revalidatePath("/admin/reports"); return { success: true as const };}catch(e){return { success: false as const, error:"Failed" };}}

export async function dropEnrollment(enrollmentId:string){try{await prisma.enrollment.update({where:{id:enrollmentId},data:{status:"DROPPED",endDate:new Date()}}); revalidatePath("/admin/students"); return ok;}catch(e){return err("Failed");}}

export async function toggleCourseStatus(courseId:string,isActive:boolean){try{await prisma.course.update({where:{id:courseId},data:{isActive}}); revalidatePath("/admin/courses"); return ok;}catch(e){return err("Failed");}}
