import Link from "next/link";
import { notFound } from "next/navigation";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent } from "@/components/ui/card";
import { StatusBadge } from "@/components/admin/shared/StatusBadge";
import { Progress } from "@/components/ui/progress";
import { Button } from "@/components/ui/button";
import { prisma } from "@/lib/prisma";
import { dropEnrollmentFormAction } from "@/lib/actions/admin";

export default async function StudentDetailPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const s=await prisma.user.findUnique({where:{id},include:{studentProfile:{include:{enrollments:{include:{course:true,attendance:{include:{schedule:true}},payments:true}}}}}});if(!s) notFound();
return <div className="space-y-6"><Card><CardContent className="p-6"><div className="flex justify-between"><div><div className="mb-2 flex h-14 w-14 items-center justify-center rounded-full bg-muted text-xl font-bold">{s.firstName[0]}{s.lastName[0]}</div><h2 className="text-2xl font-semibold">{s.firstName} {s.lastName}</h2><p>{s.studentProfile?.studentCode}</p><p>{s.email}</p><p>{s.phone}</p><p>{s.gender}</p><p>{s.address}</p></div><div><p>Guardian: {s.studentProfile?.guardianName ?? "-"}</p><p>Phone: {s.studentProfile?.guardianPhone ?? "-"}</p><p>Emergency: {s.studentProfile?.emergencyContact ?? "-"}</p></div><Button asChild><Link href={`/admin/students/${s.id}/edit`}>Edit</Link></Button></div></CardContent></Card>
<Tabs defaultValue="enrollments"><TabsList><TabsTrigger value="enrollments">Enrollments</TabsTrigger><TabsTrigger value="attendance">Attendance</TabsTrigger><TabsTrigger value="payments">Payments</TabsTrigger></TabsList>
<TabsContent value="enrollments"><table className="w-full text-sm"><thead><tr><th>Course</th><th>Start</th><th>End</th><th>Status</th><th/></tr></thead><tbody>{s.studentProfile?.enrollments.map((e:any)=><tr key={e.id}><td>{e.course.title}</td><td>{e.startDate.toLocaleDateString()}</td><td>{e.endDate?.toLocaleDateString()??"-"}</td><td><StatusBadge status={e.status}/></td><td><form action={dropEnrollmentFormAction.bind(null, e.id)}><Button size="sm" variant="outline">Drop</Button></form></td></tr>)}</tbody></table></TabsContent>
<TabsContent value="attendance" className="space-y-4">{s.studentProfile?.enrollments.map((e:any)=>{const total=e.attendance.length;const present=e.attendance.filter((a:any)=>a.status==='PRESENT').length;const pct=total?Math.round((present/total)*100):0;return <Card key={e.id}><CardContent className="p-4 space-y-2"><h4 className="font-semibold">{e.course.title}</h4><Progress value={pct}/><p>{pct}%</p><table className="w-full text-sm"><thead><tr><th>Date</th><th>Status</th><th>Note</th></tr></thead><tbody>{e.attendance.map((a:any)=><tr key={a.id}><td>{a.date.toLocaleDateString()}</td><td><StatusBadge status={a.status}/></td><td>{a.note ?? '-'}</td></tr>)}</tbody></table></CardContent></Card>})}</TabsContent>
<TabsContent value="payments"><table className="w-full text-sm"><thead><tr><th>Amount</th><th>Method</th><th>Status</th><th>Date</th><th>Receipt</th></tr></thead><tbody>{s.studentProfile?.enrollments.flatMap((e:any)=>e.payments).map((p:any)=><tr key={p.id}><td>ETB {p.amount.toLocaleString()}</td><td>{p.method}</td><td><StatusBadge status={p.status}/></td><td>{p.createdAt.toLocaleDateString()}</td><td>{p.receiptUrl?<a href={p.receiptUrl} target="_blank">View</a>:'-'}</td></tr>)}</tbody></table></TabsContent>
</Tabs></div>}
